### PR TITLE
Fix example in README

### LINKED ISSUE #8: README example does not work
When I base myself off the configuration example found in the README. configuration uploading generates an error within Concourse.

### Configuration file used
```
resource_types:
- name: gerrit
  type: docker-image
  source:
    repository: us.gcr.io/concourse-resources/gerrit-resource

resources:
- name: main-gerrit
  type: gerrit
  source:
    url: https://{{GERRIT_URL}}/
    query: status:open project:{{PROJECT_NAME}}
    username: {{USERNAME}}
    password: {{PASSWORD}}

jobs:
- name: Test-CI
  plan:
  # Trigger this job for every new patch set
  - get: main-gerrit
    version: every
    trigger: true

  - task: ls-it
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: ls

  # After a successfuly build, mark the patch set Verified +1
  - put: main-gerrit
    message: CI passed!
    labels: {Verified: 1}
```

### Error message

```
error: invalid configuration:
unknown/extra keys:
  - jobs[0].plan[2].labels
  - jobs[0].plan[2].message

```

### PR DESCRIPTION
**Pull request by lann**
Fixes #8

### CODE REVIEW

**Comment by arekmano** [comment]
This was the initial fix I tried as well. The configuration is accepted by the Concourse server, however when the job is run, there is mention of a missing "repository" param.

**Comment by arekmano** [comment]
Specifically, the error is during the "out" 

The following is the error log during the execution of the task step
```
> gerrit-resource build 0.2.0
> error processing out request: param repository required
````

**Comment by lann** [comment]
Updated the PR - try again please.

**Review by chingcodes — APPROVED** [review]

**Review by arekmano — APPROVED** [review]
This change fixes #8. README example now works correctly

**Pull request merged**
